### ISSUE TITLE
Mod doesn't fix issue on Pop OS 21.10

### ISSUE THREAD

**Issue by oyylumo** [RecursiveG/Mc122477Fix#11]
I'm running Pop_OS 21.10 minecraft version 1.18.2 and this mod doesn't appear to make any difference. I don't know what logs to include but I will happily take any debugging steps you need me to.

**Comment by RecursiveG** [comment]
Have you tried both [this](https://github.com/RecursiveG/Mc122477Fix/releases/tag/v1.0.3) and [this](https://github.com/RecursiveG/Mc122477Fix/releases/tag/v1.1.0) version?
