### ISSUE TITLE
double "/" issue still happens on 1.16.5

### ISSUE THREAD

**Issue by RangoMcRoony** [RecursiveG/Mc122477Fix#3]
i am using the latest version of fabric for 1.16.5, this mod is brilliant and stops the double "t" but i still have the double "/" happening

**Comment by RecursiveG** [comment]
Does the frequency of double typing `/` change after installing the mod? 
I don't write fabric mods so you may need to wait for @SizableShrimp to investigate this.

**Comment by RangoMcRoony** [comment]
No, at first glance it seems the same as before in terms of frequency. I'll check again tho with and without the mod to see if there is indeed a noticeable difference.

**Comment by SizableShrimp** [comment]
I remember testing '/' with no problems, and the Mixin injection points are at the same spots as @RecursiveG's forge version. I can double check.

**Comment by SizableShrimp** [comment]
I tested once more in 1.16.5 to make sure there were no version differences. I cannot reproduce the extra `/`. It could be a hardware thing where the poll happens somehow greater than 50ms after the chat screen is opened, as that would bypass the mechanism. Can you list your computer specs and what other mods you are using, if any?

**Comment by RangoMcRoony** [comment]
In that case it might just be an issue with the "/" key on my laptop. I do use other mods, mostly optimization mods that wouldnt really affect this. I do use better controls mod for fabric.

I use a Dell Latitude 3521 laptop with 8GB of ram. I'm running Ubuntu version 20.10.

**Comment by SizableShrimp** [comment]
@RangoMcRoony Can you please try the JAR file in #4? This should solve your issues on slower hardware as it is no longer based on time intervals and instead fixes the bug more closely to the source of the problem.

**Comment by RangoMcRoony** [comment]
I'll try it as soon as I'm free and let you know the results. Thank you.

**Comment by RangoMcRoony** [comment]
I had around 10mins or so free, this seems to have fixed the issue

**Comment by SizableShrimp** [comment]
Great!
