### ISSUE TITLE
Fabric Source Code

### ISSUE THREAD

**Issue by jkcoxson** [RecursiveG/Mc122477Fix#9]
I'm trying to fix bugs in this mod that I've discovered myself, and I use the fabric version. I am unable to find the fabric source code, as this repository contains the forge source. 

This doesn't seem to be on @SizableShrimp 's GitHub or their fork, is the source not publicly available?

**Comment by RecursiveG** [comment]
Please switch to a different branch: https://github.com/RecursiveG/Mc122477Fix/tree/fabric-1.16
